---
- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true
